apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-repo
  template:
    metadata:
      labels:
        app: ci-repo
    spec:
      containers:
      - name: ci-repo
        image: d00243983/ci-repo:latest
        env:
          - name: UNLEASH_URL
            value: "http://your-unleash-server-url/api"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
