apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-repo-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/your-username/cd-repo.git'  # <--- change this!
    targetRevision: HEAD
    path: overlays/dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
