apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-repo
spec:
  template:
    spec:
      containers:
        - name: ci-repo
          image: d00243983/ci-repo:latest
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          env:
            - name: UNLEASH_URL
              value: "http://your-unleash-server-url/api"
