apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - catalog-depl.yaml
  - catalog-svc.yaml
  - deployment.yaml
  - product-admin-depl.yaml
  - product-admin-svc.yaml
  - service.yaml
  - shop-front-depl.yaml
  - shop-front-svc.yaml
