apiVersion: v1
kind: Service
metadata:
  name: product-admin
  namespace: default
spec:
  selector:
    app: product-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
